### ISSUE TITLE
Using a package via <script> tag

### ISSUE THREAD

**Issue by ivanvermeyen** [calebporzio/vue-example-component#1]
Hi Caleb,

During my quest to publish my own Vue component on NPM, I found your [screencast](http://calebporzio.com/how-to-publish-a-vue-component-as-an-npm-package/).
This has been a huge help for me, since I find webpack to be extremely confusing!
So thank you for that!!! 👍 

This is what I'm currently trying to publish:
https://github.com/ivanvermeyen/vue-collapse-transition
https://www.npmjs.com/package/@ivanv/vue-collapse-transition

As you stated in your video, I can `import` or `require(...).default` the `dist` JS file to use the component, but one thing that didn't work was including my package via a `<script>` tag.

After scouring the web I finally found this Vue template that I compared with your solution:
https://github.com/Akryum/vue-share-components

When I update the `src/index.js` file to the following, I can also use the `<script>` tag.
[Demo here](https://codepen.io/ivanvermeyen/pen/LaXJKa)

```js
import CollapseTransition from './CollapseTransition'

export default CollapseTransition

export {
  CollapseTransition,
}

export function install(Vue) {
  Vue.component('CollapseTransition', CollapseTransition)
  console.log('install')
}

const plugin = {
  install,
}

let GlobalVue = null

if (typeof window !== 'undefined') {
  GlobalVue = window.Vue
} else if (typeof global !== 'undefined') {
  GlobalVue = global.Vue
}

if (GlobalVue) {
  GlobalVue.use(plugin)
  console.log('plugin')
}
```

The point is that it is automatically calling `Vue.use(...)` if `window.Vue` or `global.Vue` exists.

However, when I `import` it in a Laravel project, the above `console.logs`'s also trigger, because `window.Vue` does exist.

Do you know if this is an issue?
I did notice that the template has a specific build for the browser...

**Comment by calebporzio** [comment]
Hey @ivanvermeyen - sorry, do you mind clarifying the question in maybe more simple terms - having trouble following.

**Comment by ivanvermeyen** [comment]
Hi Caleb,

Sorry, I'll try to explain better.
My question is if I'm doing it right or if you perhaps know of a better way.
Here's the full story:

## Orignal Setup

After watching your video, I ended up with this `webpack.mix.js`:

```js
let mix = require('laravel-mix')

mix.js('src/index.js', 'dist/collapse-transition.js')

mix.webpackConfig({
    output: {
        libraryTarget: 'umd',
    }
})
```

And this `src/index.js`:

```js
import CollapseTransition from './CollapseTransition'

export default CollapseTransition
```

In my `package.json` I just refer to a `main` JS file:

```json
"main": "dist/collapse-transition.js",
```

After publishing on NPM I could `import` it in my project and then add it as a component:

```js
import CollapseTransition from '@ivanv/vue-collapse-transition'

export default {
    components: {
        CollapseTransition,
    },
}
```

## The Problem

I couldn't use it via a `<script>` tag like so:

```html
<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/@ivanv/vue-collapse-transition"></script>
```

## The "Fix"

To remedy this, I had to update the `src/index.js` to the following:

```js
import CollapseTransition from './CollapseTransition'

export default CollapseTransition

export {
  CollapseTransition,
}

export function install(Vue) {
  Vue.component('CollapseTransition', CollapseTransition)
}

const plugin = {
  install,
}

let GlobalVue = null

if (typeof window !== 'undefined') {
  GlobalVue = window.Vue
} else if (typeof global !== 'undefined') {
  GlobalVue = global.Vue
}

if (GlobalVue) {
  GlobalVue.use(plugin)
}
```

## My New "Problem"

Now everything works, but the `install` function in `src/index.js` always runs.
Even when you manually import it like this:

```js
import CollapseTransition from '@ivanv/vue-collapse-transition'
```

So adding it as a component is no longer needed, because it tries to add the component twice then:

```js
import CollapseTransition from '@ivanv/vue-collapse-transition'

export default {
    components: {
        CollapseTransition, // Not needed...
    },
}
```

But it doesn't give any errors if you do either.

I was wondering if this is the proper way to handle it.

**Comment by calebporzio** [comment]
I see. Interesting. I have never needed to make the component available via CDN, so haven't encountered this problem.

The reason that `install` is running when you import the component is probably because window.Vue is detected at runtime? I would just be googling for solutions to this or looking at other plugin's `index.js` files.

Sorry I can't be more of a help. But if you find a good solution, would love to see it here.

**Comment by ivanvermeyen** [comment]
> The reason that install is running when you import the component is probably because window.Vue is detected at runtime? I would just be googling for solutions to this or looking at other plugin's index.js files.

Exactly. So far it doesn't create any problems, but it bugs me (maybe it shouldn't) :)
I will keep an eye out for other examples and let you know if I find anything useful.

Thanks for your time and btw, great work with Livewire!
What I saw so far looks amazing!
